/*
 * Test data strategy for org.softlang.model.Company.
 *
 * Generated by JMLUnitNG 1.3 (103), 2012-08-21 11:21 -0300.
 * (do not modify this comment, it is used by JMLUnitNG clean-up routines)
 */

package org.softlang.model.Company_JML_Data;


import org.jmlspecs.jmlunitng.iterator.ObjectArrayIterator;
import org.jmlspecs.jmlunitng.iterator.RepeatedAccessIterator;
import org.softlang.model.PackageStrategy_org_softlang_model_Department;
/**
 * Test data strategy for org.softlang.model.Company. Provides
 * class-scope test values for type org.softlang.model.Department.
 * 
 * @author JMLUnitNG 1.3 (103)
 * @version 2012-08-21 11:21 -0300
 */
public class ClassStrategy_org_softlang_model_Department 
  extends PackageStrategy_org_softlang_model_Department {
  /**
   * @return class-scope values for type org.softlang.model.Department.
   */
  public RepeatedAccessIterator<?> classValues() {
    return new ObjectArrayIterator<Object>
    (new Object[] 
  	 { /* add class-scope org.softlang.model.Department values or generators here */ });
  }

  /**
   * The use of reflection can be controlled here for  
   * parameters of type org.softlang.model.Department
   * in this class by changing the parameters to <code>setReflective</code>
   * and <code>setMaxRecursionDepth<code>. 
   * In addition, the data generators used can be changed by adding 
   * additional data class lines, or by removing some of the automatically 
   * generated ones. Note that lower-level strategies can override any 
   * behavior specified here by calling the same control methods in 
   * their own constructors.
   *
   * @see NonPrimitiveStrategy#addDataClass(Class<?>)
   * @see NonPrimitiveStrategy#clearDataClasses()
   * @see ObjectStrategy#setReflective(boolean)
   * @see ObjectStrategy#setMaxRecursionDepth(int)
   */
  public ClassStrategy_org_softlang_model_Department() {
    super();
    setReflective(false);
    // uncomment to control the maximum reflective instantiation
    // recursion depth, 0 by default
    // setMaxRecursionDepth(0);
  }
}
