/*
 * Test data strategy for org.softlang.model.Company.
 *
 * Generated by JMLUnitNG 1.3 (103), 2012-08-21 11:23 -0300.
 * (do not modify this comment, it is used by JMLUnitNG clean-up routines)
 */

 
package org.softlang.model.Company_JML_Data;

import org.jmlspecs.jmlunitng.iterator.ObjectArrayIterator;
import org.jmlspecs.jmlunitng.iterator.RepeatedAccessIterator;

/**
 * Test data strategy for org.softlang.model.Company. Provides
 * test values for parameter "String pname" 
 * of method "Company(String)". 
 * 
 * @author JMLUnitNG 1.3 (103)
 * @version 2012-08-21 11:23 -0300
 */
public class Company__String_pname__10__pname
  extends ClassStrategy_java_lang_String {
  /**
   * @return local-scope values for parameter 
   *  "String pname".
   */
  public RepeatedAccessIterator<?> localValues() {
  	return new ObjectArrayIterator<Object>
  	(new Object[]
  	 { /* add local-scope java.lang.String values or generators here */ });
  }
}
