/*
 * Test data strategy for package org.softlang.model.
 *
 * Generated by JMLUnitNG 1.3 (103), 2012-08-19 16:01 -0300.
 * (do not modify this comment, it is used by JMLUnitNG clean-up routines)
 */

 package org.softlang.model;

import org.jmlspecs.jmlunitng.iterator.ObjectArrayIterator;
import org.jmlspecs.jmlunitng.iterator.RepeatedAccessIterator;
import org.jmlspecs.jmlunitng.strategy.StringStrategy;

/**
 * Test data strategy for package org.softlang.model. Provides
 * package-scope test values for type java.lang.String.
 * 
 * @author JMLUnitNG 1.3 (103)
 * @version 2012-08-19 16:01 -0300
 */
public class PackageStrategy_java_lang_String 
  extends StringStrategy {
  /**
   * @return package-scope values for type java.lang.String.
   */
  public RepeatedAccessIterator<?> packageValues() {
    return new ObjectArrayIterator<Object>
    (new Object[] 
     { /* add package-scope java.lang.String values or generators here */ });
  }
}
