/*
 * Test data strategy for org.softlang.model.Employee.
 *
 * Generated by JMLUnitNG 1.3 (103), 2012-08-21 11:25 -0300.
 * (do not modify this comment, it is used by JMLUnitNG clean-up routines)
 */

package org.softlang.model.Employee_JML_Data;


import org.jmlspecs.jmlunitng.iterator.ObjectArrayIterator;
import org.jmlspecs.jmlunitng.iterator.RepeatedAccessIterator;
import org.softlang.model.PackageStrategy_java_lang_String;
/**
 * Test data strategy for org.softlang.model.Employee. Provides
 * class-scope test values for type java.lang.String.
 * 
 * @author JMLUnitNG 1.3 (103)
 * @version 2012-08-21 11:25 -0300
 */
public class ClassStrategy_java_lang_String 
  extends PackageStrategy_java_lang_String {
  /**
   * @return class-scope values for type java.lang.String.
   */
  public RepeatedAccessIterator<?> classValues() {
    return new ObjectArrayIterator<Object>
    (new Object[] 
  	 { /* add class-scope java.lang.String values or generators here */ });
  }
}
