/*
 * Test data strategy for org.softlang.model.Employee.
 *
 * Generated by JMLUnitNG 1.3 (103), 2012-08-19 16:01 -0300.
 * (do not modify this comment, it is used by JMLUnitNG clean-up routines)
 */

package org.softlang.model.Employee_JML_Data;


import org.jmlspecs.jmlunitng.iterator.ObjectArrayIterator;
import org.jmlspecs.jmlunitng.iterator.RepeatedAccessIterator;
import org.softlang.model.PackageStrategy_double;
/**
 * Test data strategy for org.softlang.model.Employee. Provides
 * class-scope test values for type double.
 * 
 * @author JMLUnitNG 1.3 (103)
 * @version 2012-08-19 16:01 -0300
 */
public class ClassStrategy_double 
  extends PackageStrategy_double {
  /**
   * @return class-scope values for type double.
   */
  public RepeatedAccessIterator<?> classValues() {
    return new ObjectArrayIterator<Object>
    (new Object[] 
  	 { /* add class-scope double values or generators here */ });
  }
}
