/*
 * Test data strategy for org.softlang.model.Employee.
 *
 * Generated by JMLUnitNG 1.3 (103), 2012-08-19 16:01 -0300.
 * (do not modify this comment, it is used by JMLUnitNG clean-up routines)
 */

 
package org.softlang.model.Employee_JML_Data;

import org.jmlspecs.jmlunitng.iterator.ObjectArrayIterator;
import org.jmlspecs.jmlunitng.iterator.RepeatedAccessIterator;

/**
 * Test data strategy for org.softlang.model.Employee. Provides
 * test values for parameter "double salary" 
 * of method "void setSalary(double)". 
 * 
 * @author JMLUnitNG 1.3 (103)
 * @version 2012-08-19 16:01 -0300
 */
public class setSalary__double_salary__0__salary
  extends ClassStrategy_double {
  /**
   * @return local-scope values for parameter 
   *  "double salary".
   */
  public RepeatedAccessIterator<?> localValues() {
  	return new ObjectArrayIterator<Object>
  	(new Object[]
  	 { /* add local-scope double values or generators here */ });
  }
}
